"""Actualización base de datos

Revision ID: a5d1ebb8771e
Revises: 
Create Date: 2024-11-20 12:44:40.365445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d1ebb8771e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email', new_column_name='direction')
        batch_op.alter_column('password', new_column_name='slogan')
        batch_op.add_column(sa.Column('contacto', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('direction', new_column_name='users')
        batch_op.drop_column('contacto')

    # ### end Alembic commands ###
