"""Se crean tablas user y data

Revision ID: b72c8d5c80cb
Revises: 
Create Date: 2025-02-12 10:29:08.058633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72c8d5c80cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number_visit', sa.Integer(), nullable=False),
    sa.Column('userAgent', sa.String(), nullable=False),
    sa.Column('screenWidth', sa.Integer(), nullable=False),
    sa.Column('screenHeight', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('timeZone', sa.String(length=150), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_visit', name='uq_data_number_visit')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=120), nullable=False),
    sa.Column('slogan', sa.String(length=128), nullable=False),
    sa.Column('contacto', sa.String(length=40), nullable=False),
    sa.Column('image_user', sa.String(length=250), nullable=False),
    sa.Column('open_time', sa.String(length=5), nullable=False),
    sa.Column('close_time', sa.String(length=5), nullable=False),
    sa.Column('time_register_user', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction', name='uq_users_direction'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('data')
    # ### end Alembic commands ###
