"""Se agrega la columna imagen

Revision ID: c7037fc570f5
Revises: a5d1ebb8771e
Create Date: 2024-11-21 12:51:09.337082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7037fc570f5'
down_revision = 'a5d1ebb8771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_user', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_user')

    # ### end Alembic commands ###
